# Generated by Django 5.2.4 on 2025-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profpictures/%Y/%m/%d/', verbose_name='Set your profile picture'),
        ),
    ]
